#version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    hostname: zookeeper
    container_name: proj_zookeeper
    ports:
      - '2181:2181'
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
  # --------------------------------------
  broker:
    image: confluentinc/cp-kafka:7.4.0
    hostname: broker
    container_name: proj_broker
    depends_on:
      - zookeeper
    ports:
      - '29092:29092'
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
  minio:
    image: bitnami/minio:latest
    container_name: proj_minio_blob
    # user: "1000"
    ports:
      - '9000:9000'
      - '9001:9001'
    networks:
      - minionetwork
    volumes:
      - "./apps/minio_data:/minio/data" #Default bucket location is: /bitnami/minio/data/minio-bucket.
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
      - MINIO_DEFAULT_BUCKETS=minio-bucket
      # - MINIO_DATA_DIR="/minio/data" #Causes errors when enabled.
      # - MINIO_FORCE_NEW_KEYS=yes
      # - MINIO_BROWSER=on
      - MINIO_SCHEME=http
# ----------------------------
networks:
  minionetwork:
    driver: bridge
# ----------------------------
volumes:
  minio_data:
    driver: local
# ----------------------------